[package]
name = "beginner-rocket-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
rocket = { version = "0.5.0", features = ["json"] }
serde_json = "1.0.114"
